### PR TITLE
Use ES6 imports for codemirror css

### PR DESCRIPTION
**Pull request by blink1073**
Not sure what the deal is with the line endings in codemirror.d.ts, did you check something in on Windows?

### CODE REVIEW

**Comment by blink1073** [comment]
cc @sccolbert

I'd argue that hard-coding an path with `node_modules` is not a valid solution, because you have no way of knowing that the path needs to be configured for `SystemJS`.  It appears we've hit a limitation where you _must_ use a global CSS transform to make this work with browserify without hard-coding a path.

**Comment by sccolbert** [comment]
I think we should ignore browserify. `SystemJS` also has the ability to bundle. So we can use a single System config if and when we decide to bundle.

**Comment by blink1073** [comment]
So you're advocating for the testing strategy in [phosphor-plugins](https://github.com/phosphorjs/phosphor-plugins/tree/master/test) for all repos moving forward?

**Comment by sccolbert** [comment]
Yeah, I think so. Browserify got us off the ground, but going forward I dont see how it will be manageable.

**Pull request closed without merging**
